version: '2'

services:
  
#  elastic_hq:
#    image: elastichq/elasticsearch-hq
#    container_name: elastic_hq
#    hostname: elastic_hq
#    ports:
#      - 5000:5000
  
  elastic_search_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elastic_search_2
    hostname: elastic_search_2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic
   
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elastic_search_2
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic   

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: kafka-cluster
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "simpletalk_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
  kafka-ui:
    image: digitsy/kafka-magic
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:80"
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"
    # http://localhost:8080/
      
  redis:
    image: redis:6.2.5
    hostname: redis
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    links: 
      - redis-commander 

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    container_name: redis-commander
    hostname: redis-commander
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    # http://localhost:8081/
      
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ms-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      # user: sa
      - SA_PASSWORD=@Qwert123456789
      - MSSQL_PID=Developer
        
  postgresql:
    image: "clkao/postgres-plv8:latest"
    hostname: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    # Username=postgres
    # password=postgres
    
# docker network create -d bridge elastic
networks:
  elastic:
    driver: bridge
    
volumes:
  elasticsearch-data:
